[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "tp3"
version = "0.0.1"

[tool.scikit-build]
build-dir = "build" # Don't use a temporary build directory
